### ISSUE TITLE
it didn't work when i follow the example

### ISSUE THREAD

**Issue by kobeCan** [CesiumGS/cesium-webpack-example#2]
hello, when my **webpack.config.js** is same as yours,  and start the app, CLI tells me: 
```
WARNING in ./node_modules/cesium/Source/Core/TaskProcessor.js
 140:27-34 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
  @ ./node_modules/cesium/Source/Core/TaskProcessor.js
  @ ./node_modules/cesium/Source/Core/QuantizedMeshTerrainData.js
  @ ./node_modules/cesium/Source/Cesium.js
  @ ./src/index.js
  @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

 WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js
 57:15-22 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
  @ ./node_modules/cesium/Source/Core/buildModuleUrl.js
  @ ./node_modules/cesium/Source/Cesium.js
  @ ./src/index.js
  @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

 WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js
 77:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
  @ ./node_modules/cesium/Source/Core/buildModuleUrl.js
  @ ./node_modules/cesium/Source/Cesium.js
  @ ./src/index.js
  @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js;
```

the browser told me :

```
Error constructing CesiumWidget.
Visit http://get.webgl.org to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:

Error: Cannot find module "."
Error: Cannot find module "."
    at webpackMissingModule (http://localhost:8080/cesium.js:30375:69)
    at buildModuleUrl (http://localhost:8080/cesium.js:30375:147)
    at new Globe (http://localhost:8080/cesium.js:192424:34)
    at new CesiumWidget (http://localhost:8080/cesium.js:218537:25)
    at new Viewer (http://localhost:8080/cesium.js:250613:28)
    at Object.<anonymous> (http://localhost:8080/cesium.js:232598:14)
    at __webpack_require__ (http://localhost:8080/cesium.js:55:30)
    at Object.<anonymous> (http://localhost:8080/cesium.js:252799:18)
    at __webpack_require__ (http://localhost:8080/cesium.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/cesium.js:26:23)
```
**I promise that my browser is updated.**

**Comment by ggetz** [comment]
Hi there, until the next Cesium release on November 1, make sure to point your version of cesium to this non-release version: https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/blob/master/package.json#L18, or clone the [GitHub repo](https://github.com/AnalyticalGraphicsInc/cesium) and build.

The changes required for building cesium with webpack are not in the last release.

**Comment by kobeCan** [comment]
thanks a lot for your reply！ It works!
